[workspace]
members = [
    "crates/landmass",
    "crates/bevy_landmass",
    "crates/landmass_rerecast",
]
resolver = "2"

[patch.crates-io]
dodgy_2d = { git = "https://github.com/andriyDev/dodgy", branch = "dependabot/cargo/glam-0.32.0" }
